### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf7 in position 2: ordinal not in range(128)

### ISSUE THREAD

**Issue by keke18532** [yanhaiming56/SynthText_Chinese_py3#3]
text_utils.py", line 436, in __init__
    self.char_freq = cp.load(f)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf7 in position 2: ordinal not in range(128)

**Comment by light201212** [comment]
did you solve it by using encoding = "iso-8859-1"?
